# Generated by Django 3.2.12 on 2024-02-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_cheesetype_pizza_pizzasize_saucestype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheesetype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pizzasize',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='saucestype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
