# Generated by Django 3.2.12 on 2024-02-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_pizzauser'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('cardnumber', models.CharField(max_length=16)),
                ('card_expiry_month', models.IntegerField()),
                ('card_expiry_year', models.IntegerField()),
                ('card_cvv', models.CharField(max_length=4)),
            ],
        ),
    ]
