# Generated by Django 3.2.12 on 2024-02-19 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_deliverydetails_deliverydetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzauser',
            name='detail',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.deliverydetail'),
        ),
    ]
