# Generated by Django 3.2.12 on 2024-02-19 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_pizza_cheese'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='sauces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.saucestype'),
        ),
    ]
