# Generated by Django 5.0.2 on 2024-02-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_pizza_sauces'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzauser',
            name='arrived_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
